// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOnFSLM7nhJ8Jc7JW6f8jz7Xv8fCMZ1cA',
    appId: '1:137296514629:web:9e9d7321dc16f4b8835d2c',
    messagingSenderId: '137296514629',
    projectId: 'hrms-34edc',
    authDomain: 'hrms-34edc.firebaseapp.com',
    storageBucket: 'hrms-34edc.firebasestorage.app',
    measurementId: 'G-ESN637FF64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjDSu5dzrt538riYOWGoRBnFBllI34iT4',
    appId: '1:137296514629:android:969e53fb7a30ce4b835d2c',
    messagingSenderId: '137296514629',
    projectId: 'hrms-34edc',
    storageBucket: 'hrms-34edc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4eKSwkztI7wwm1HP3iVn8hg7AaszKjeU',
    appId: '1:137296514629:ios:389102d7ee8c0c84835d2c',
    messagingSenderId: '137296514629',
    projectId: 'hrms-34edc',
    storageBucket: 'hrms-34edc.firebasestorage.app',
    iosBundleId: 'com.tawreda.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4eKSwkztI7wwm1HP3iVn8hg7AaszKjeU',
    appId: '1:137296514629:ios:1bb27532b47985ff835d2c',
    messagingSenderId: '137296514629',
    projectId: 'hrms-34edc',
    storageBucket: 'hrms-34edc.firebasestorage.app',
    iosBundleId: 'com.example.employeeMangement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOnFSLM7nhJ8Jc7JW6f8jz7Xv8fCMZ1cA',
    appId: '1:137296514629:web:e5fbd00f550ade9d835d2c',
    messagingSenderId: '137296514629',
    projectId: 'hrms-34edc',
    authDomain: 'hrms-34edc.firebaseapp.com',
    storageBucket: 'hrms-34edc.firebasestorage.app',
    measurementId: 'G-H35EKLFR3L',
  );
}
