name: Build iOS IPA & Android APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build iOS & Android
    runs-on: macos-15  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  


      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: 'stable'
          architecture: x64

      - name: Verify Flutter version
        run: flutter --version

      - name: Get Flutter dependencies
        run: flutter pub get


      - name: Print Xcode version
        run: xcodebuild -version

      - name: Build Android APK
        run: flutter build apk --release


      - name: Update CocoaPods repo
        run: pod repo update
        working-directory: ios

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Create Payload folder and move Runner.app
        run: |
          mkdir Payload
          mv Runner.app Payload/
        working-directory: build/ios/iphoneos

      - name: Create IPA
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload/
        working-directory: build/ios/iphoneos

   
      - name: Upload Android APK to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          tag: v1.7
          overwrite: true

      - name: Upload iOS IPA to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          asset_name: FlutterIpaExport.ipa
          tag: v1.7
          overwrite: true


      - name: Update release description
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          tag_name: v1.7
          body: |
            Release built with:
            - Flutter 3.32.0
            - Xcode 16.1 (macOS 15)
            - Android APK + iOS IPA attached